tunnel: 8ae4e2d0-2c36-4df0-97cb-6f781730c8c4
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: dev-admin.deedims.biz.id
    service: http://frontend:80
  - service: http_status:404
